import type { FeedItem, DocumentType, Attachment } from "@/lib/types";

export const MOCK_FEED: FeedItem[] = [
  {
    id: "item-ks-johnson-utility-solar-1",
    sourceId: "johnson_county_planning",
    fileUrl: "https://jocogov.org/dept/planning/docs/2025-10-27-solar-agenda.pdf",
    contentHash: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6",
    bytesSize: 524288,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    title: "Proposed permitting requirements for utility-scale solar",
    entity: "Johnson County Planning Board",
    jurisdiction: "Johnson County, KS",
    counties: ["Johnson"],
    meetingDate: new Date().toISOString(),
    docTypes: ["Agenda", "Staff Memo"],
    impact: "High",
    stage: "Hearing",
    topics: ["solar zoning", "renewable incentive", "land use"],
    hits: { "solar zoning": 3, setback: 2 },
    attachments: [
      { id: "a1", title: "Agenda", type: "Agenda", pageCount: 15 },
      { id: "a2", title: "Staff Memo", type: "Staff Memo", pageCount: 6 },
    ],
    extractedText: [
      "Staff recommends establishing a conditional use permit for utility-scale solar facilities, subject to performance standards including setbacks, buffering, and decommissioning.",
      "Setbacks: A minimum of 300 feet from residential structures, with increased distances adjacent to designated scenic corridors.",
      "Environmental review: Projects exceeding 50 acres require a third-party study on stormwater and wildlife impacts.",
      "Public comment summary: 37 submissions, with mixed sentiment on visual impacts and agricultural land conversion.",
    ],
    pdfPreview: [
      "Agenda p.1 — Call to Order, Approval of Minutes, New Business",
      "Staff Memo p.2 — Background: growth in regional solar proposals",
      "Staff Memo p.4 — Proposed standards: setbacks, screening, glare",
      "Appendix A — Draft ordinance excerpts",
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-ks-sedgwick-cell-phone-ban-1",
    sourceId: "sedgwick_county_schools",
    fileUrl: "https://usd259.org/board/minutes/2025-10-24-minutes.pdf",
    contentHash: "b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1",
    bytesSize: 256000,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    title: "Cell phone use policy in classrooms",
    entity: "Sedgwick County School Board",
    jurisdiction: "Sedgwick County, KS",
    counties: ["Sedgwick"],
    meetingDate: new Date(Date.now() - 86400000 * 3).toISOString(),
    docTypes: ["Minutes"],
    impact: "Medium",
    stage: "Adopted",
    topics: ["education", "cell phone ban"],
    hits: { "cell phone ban": 4, curriculum: 1 },
    attachments: [
      { id: "b1", title: "Minutes", type: "Minutes", pageCount: 22 },
    ],
    extractedText: [
      "The Board adopted policy 5131.8 restricting student cell phone use during instructional hours, with exceptions for documented medical needs and IEP/504 accommodations.",
      "Enforcement: First violation — warning and parent notification; subsequent violations — progressive discipline at principal discretion.",
      "Rationale: Reduce disruptions and improve attention; references to peer district outcomes.",
    ],
    pdfPreview: [
      "Minutes p.3 — Superintendent report",
      "Minutes p.8 — Public comments (12 speakers)",
      "Minutes p.12 — Motion and vote record",
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-ks-douglas-bike-lanes-1",
    sourceId: "douglas_county_commission",
    fileUrl: "https://douglascountyks.org/commission/agenda/2025-10-22-agenda.pdf",
    contentHash: "c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2",
    bytesSize: 412000,
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    title: "Expansion of protected bike lanes on 23rd St",
    entity: "Douglas County Commission",
    jurisdiction: "Douglas County, KS",
    counties: ["Douglas"],
    meetingDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    docTypes: ["Agenda", "Staff Memo"],
    impact: "Low",
    stage: "Work Session",
    topics: ["transit", "bike lanes"],
    hits: { "bike lanes": 5, transit: 2 },
    attachments: [
      { id: "c1", title: "Agenda", type: "Agenda", pageCount: 10 },
      { id: "c2", title: "Staff Memo", type: "Staff Memo", pageCount: 4 },
    ],
    extractedText: [
      "Proposal outlines extension of protected lanes from Massachusetts St to O'Connell Rd, including physical separators and intersection treatments.",
      "Funding: CMAQ grant application under consideration; city match of 20% anticipated.",
    ],
    pdfPreview: [
      "Agenda p.2 — Public Works update",
      "Memo p.3 — Crash data and safety benefits",
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "item-ks-wyandotte-zoning-hearing-1",
    sourceId: "wyandotte_city_council",
    fileUrl: "https://wycokck.org/council/ordinances/2025-10-20-ord-draft.pdf",
    contentHash: "d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3",
    bytesSize: 680000,
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    title: "Zoning hearing for mixed-use development at Riverfront",
    entity: "Wyandotte City Council",
    jurisdiction: "Wyandotte County, KS",
    counties: ["Wyandotte"],
    meetingDate: new Date(Date.now() - 86400000 * 7).toISOString(),
    docTypes: ["Agenda", "Ordinance"],
    impact: "High",
    stage: "Hearing",
    topics: ["zoning", "land use"],
    hits: { zoning: 6, "mixed-use": 3 },
    attachments: [
      { id: "d1", title: "Agenda", type: "Agenda", pageCount: 18 },
      { id: "d2", title: "Ordinance Draft", type: "Ordinance", pageCount: 12 },
    ],
    extractedText: [
      "Mixed-use PUD at Riverfront introduces active ground-floor uses and reduced parking ratios with TDM measures.",
      "Community concerns: traffic circulation and shadow impacts; staff recommends conditions for loading and hours of operation.",
    ],
    pdfPreview: [
      "Agenda p.1 — Public hearing notice",
      "Ordinance draft p.5 — Development standards",
    ],
    updatedAt: new Date().toISOString(),
  },
  ...Array.from({ length: 14 }).map((_, i): FeedItem => ({
    id: `item-ks-johnson-generated-${i + 2}`,
    sourceId: i % 2 ? "johnson_county_schools" : "johnson_county_planning",
    fileUrl: `https://jocogov.org/docs/2025-10-${20 - i}-doc.pdf`,
    contentHash: `hash${i}abcdef1234567890`,
    bytesSize: 100000 + (i * 10000),
    createdAt: new Date(Date.now() - 86400000 * (3 + i)).toISOString(),
    title: i % 2 ? `Curriculum review update ${i + 2}` : `Subdivision regulation amendments ${i + 2}`,
    entity: i % 2 ? "Johnson County School Board" : "Johnson County Planning Board",
    jurisdiction: "Johnson County, KS",
    counties: ["Johnson"],
    meetingDate: new Date(Date.now() - 86400000 * (2 + i)).toISOString(),
    docTypes: ["Agenda" as DocumentType],
    impact: (i % 3 === 0 ? "High" : i % 3 === 1 ? "Medium" : "Low") as FeedItem["impact"],
    stage: i % 2 ? "Draft" : "Work Session",
    topics: i % 2 ? ["education"] : ["zoning"],
    hits: i % 2 ? { curriculum: 1 + (i % 3) } : { zoning: 2 + (i % 4) },
    attachments: [
      { id: `g${i}-1`, title: "Agenda", type: "Agenda" as DocumentType, pageCount: 8 + (i % 5) } as Attachment,
    ],
    updatedAt: new Date().toISOString(),
  })),
];
